Controllers/PrincipalController.cs
using Microsoft.AspNetCore.Mvc;

namespace IngeLab.Controllers
{
    public class PrincipalController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=5, minimum-scale=1.0s" />
    <title>@ViewData["Title"] - IngeLab</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/Login.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/IngeLab.styles.css" asp-append-version="true" />
</head>
<body>

    @if (ViewData["HideNavbar"] == null) {
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light navbar-transparente-custom mb-3">
                <div class="container-fluid">

                    <a class="navbar-brand" asp-controller="Principal" asp-action="Index">
                        <img src="https://i.imgur.com/pSxLhKg.jpeg" alt="Logo IngeLab" class="logo-navbar">
                        <span>IngeLab</span>
                    </a>

                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Login</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
    }

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>